version: '3'
services:
  node-auth-app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - node-auth-mongo

  node-auth-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - node-auth-mongo:/data/db
    ports:
      - "27017:27017"
  
  im-mongo-express:
    image: mongo-express
    container_name: node-auth-mongo-express
    restart: always
    ports:
      - 3002:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: node-auth-mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    links:
      - node-auth-mongo
  
volumes:
  node-auth-mongo:
