version: '3'
services:
  node-auth-app:
    build:
      dockerfile: Dockerfile
      context: ./auth
    volumes:
      - /app/node_modules
      - ./users:/app
    ports:
      - "3001:3001"
    environment:
      - MONGO_USER=jepymongo
      - MONGO_PASSWORD=jepymongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jepymongo
      - MONGO_INITDB_ROOT_PASSWORD=jepymongo
    volumes:
      - mongodb:/data/db


volumes:
  mongodb:


# docker run -d --name nats-streaming -p 4222:4222 -p 8222:8222 nats-streaming