version: '3'
services:
  node-users-app:
    build:
      dockerfile: Dockerfile
      context: ./users
    volumes:
      - /app/node_modules
      - ./users:/app
    ports:
      - "3001:3001"
    environment:
      - MONGO_USER=jepymongo
      - MONGO_PASSWORD=jepymongo
    depends_on:
      - mongo
      
  node-shopping-app:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    volumes:
      - /app/node_modules
      - ./shopping:/app
    ports:
      - "3002:3002"
    environment:
      - MONGO_USER=jepymongo
      - MONGO_PASSWORD=jepymongo
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jepymongo
      - MONGO_INITDB_ROOT_PASSWORD=jepymongo
    volumes:
      - mongodb:/data/db


volumes:
  mongodb:
     