version: '3'
services:
  nat-streaming-server:
    image: nats-streaming
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server

  node-users-app:
    build:
      dockerfile: Dockerfile
      context: ./users
    volumes:
      - /app/node_modules
      - ./users:/app
    ports:
      - "3001:3001"
    environment:
      - MONGO_USER=jepymongo
      - MONGO_PASSWORD=jepymongo
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - mongo
      - nat-streaming-server
      
  node-shopping-app:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    volumes:
      - /app/node_modules
      - ./shopping:/app
    ports:
      - "3002:3002"
    environment:
      - MONGO_USER=jepymongo
      - MONGO_PASSWORD=jepymongo
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jepymongo
      - MONGO_INITDB_ROOT_PASSWORD=jepymongo
    volumes:
      - mongodb:/data/db


volumes:
  mongodb:


# docker run -d --name nats-streaming -p 4222:4222 -p 8222:8222 nats-streaming