---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-dpl
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        imagePullPolicy: Always
        image: aputrabay/express:latest
        ports:
        - containerPort: 3001
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi