name: practicalgitops.app
env:
  DOCKERHUB_TAG: "${{ secrets.USERNAME/cheffapp-users}}"
  DOCKERFILE_PATH: users
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "${{ env.DOCKERFILE_PATH }}"
          push: true
          tags: "${{ env.DOCKERHUB_TAG }}:latest"
  
