name: push users microservice to dockerhub
env:
  DOCKERHUB_TAG: 'jespstpierre/cheffapp-stores'
  DOCKERFILE_PATH: ./stores
on:
  push:
    branches:
      - main
    paths:
      - "stores/**"
      - "!**/README.md"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          node-version: 16
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "${{ env.DOCKERFILE_PATH }}"
          push: true
          tags: "${{ env.DOCKERHUB_TAG }}:latest"
          node-version: 16
          
  
